

DECLARE @VLRTAXA DECIMAL
  DECLARE @NUFIN_NEW INT
  DECLARE @VLRNEW DECIMAL 
  DECLARE @VLRFIN DECIMAL
  DECLARE @NUFIN_DELT INT
  DECLARE @VLRDESB_DLT DECIMAL

  SET @VLRTAXA = (SELECT CARTAODESC FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND DHBAIXA IS NOT NULL)
  
  IF (@CODNAT = 1010300)
  BEGIN
  
  	--- Realiza o processo de verificar o arquivos novo com o valor da diferença como despesa.
	  IF(@VLRBAIXA > 0 AND @DHBAIXA IS NOT NULL)
	  BEGIN
	  	IF EXISTS(SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND DHBAIXA IS NULL)
	  	BEGIN
	  		SET @NUFIN_NEW =  (SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND DHBAIXA IS NULL)
	  		SET @VLRNEW = (SELECT VLRDESDOB FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND DHBAIXA IS NULL)
	  		SET @VLRFIN = (@VLRNEW + @VLRTAXA)
	  
	  		UPDATE TGFFIN SET VLRDESDOB = @VLRFIN, CODNAT = 1010600, DHBAIXA =GETDATE(), VLRBAIXA = @VLRFIN, RECDESP = -1 WHERE NUFIN = @NUFIN_NEW
	  	END
	  END
	
	--- Realiza o processo a esclusao do arquivo novo quando o documento original for estornado.
	  IF((@VLRBAIXA IS NULL OR @VLRBAIXA < = 0) AND @DHBAIXA IS NULL )
	  BEGIN
		IF EXISTS(SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND VLRDESDOB IS NOT NULL AND DHBAIXA IS NOT NULL)
		BEGIN	
			SET @NUFIN_DELT =  (SELECT NUFIN FROM TGFFIN WHERE NUNOTA = @NUNOTA AND DESDOBRAMENTO = @DESSOBRAMENTO AND VLRDESDOB IS NOT NULL AND DHBAIXA IS NOT NULL)
			IF EXISTS(SELECT NUFIN FROM TGFFIN WHERE NUFIN = @NUFIN_DELT AND VLRBAIXA > 0 AND DHBAIXA IS NOT NULL)
			BEGIN
				SET @VLRDESB_DLT = (SELECT VLRDESDOB FROM TGFFIN WHERE NUFIN = @NUFIN_DELT)
				UPDATE TGFFIN SET VLRBAIXA= '', DHBAIXA = NULL WHERE NUFIN = @NUFIN_DELT
				UPDATE TGFFIN SET VLRDESDOB= (VLRDESDOB - CARTAODESC + @VLRDESB_DLT) WHERE NUFIN = @NUFIN
			END
			DELETE FROM TGFFRE WHERE NUFIN = @NUFIN_DELT
			DELETE FROM TGFFIN WHERE NUFIN = @NUFIN_DELT
		END
	   END
   END